#Makefile for Red Hat Documentation
#Created by Jeff Fearn <jfearn@redhat.com>
#Copyright Red Hat Inc. 2006

XML_LANG	= en-US

BRAND		= JBoss

OTHER_LANGS	= de-DE es-ES fr-FR ja-JP pt-BR zh-CN

COMMON_CONFIG  = /usr/share/publican
include $(COMMON_CONFIG)/make/Makefile.common


