#Makefile for JBoss_Messaging_User_Guide

XML_LANG	= en-US

BRAND		= JBoss

#OTHER_LANGS	= de-DE es-ES fr-FR ja-JP pt-BR zh-CN

COMMON_CONFIG  = /usr/share/publican
include $(COMMON_CONFIG)/make/Makefile.common

