/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jboss_messaging_core_asyncio_impl_AsynchronousFileImpl */

#ifndef _Included_org_jboss_messaging_core_asyncio_impl_AsynchronousFileImpl
#define _Included_org_jboss_messaging_core_asyncio_impl_AsynchronousFileImpl
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: log */
/* Inaccessible static: loaded */
/*
 * Class:     org_jboss_messaging_core_asyncio_impl_AsynchronousFileImpl
 * Method:    init
 * Signature: (Ljava/lang/String;ILorg/jboss/messaging/core/logging/Logger;)J
 */
JNIEXPORT jlong JNICALL Java_org_jboss_messaging_core_asyncio_impl_AsynchronousFileImpl_init
  (JNIEnv *, jclass, jstring, jint, jobject);

/*
 * Class:     org_jboss_messaging_core_asyncio_impl_AsynchronousFileImpl
 * Method:    write
 * Signature: (JJJLjava/nio/ByteBuffer;Lorg/jboss/messaging/core/asyncio/AIOCallback;)V
 */
JNIEXPORT void JNICALL Java_org_jboss_messaging_core_asyncio_impl_AsynchronousFileImpl_write
  (JNIEnv *, jobject, jlong, jlong, jlong, jobject, jobject);

/*
 * Class:     org_jboss_messaging_core_asyncio_impl_AsynchronousFileImpl
 * Method:    read
 * Signature: (JJJLjava/nio/ByteBuffer;Lorg/jboss/messaging/core/asyncio/AIOCallback;)V
 */
JNIEXPORT void JNICALL Java_org_jboss_messaging_core_asyncio_impl_AsynchronousFileImpl_read
  (JNIEnv *, jobject, jlong, jlong, jlong, jobject, jobject);

/*
 * Class:     org_jboss_messaging_core_asyncio_impl_AsynchronousFileImpl
 * Method:    fill
 * Signature: (JJIJB)V
 */
JNIEXPORT void JNICALL Java_org_jboss_messaging_core_asyncio_impl_AsynchronousFileImpl_fill
  (JNIEnv *, jclass, jlong, jlong, jint, jlong, jbyte);

/*
 * Class:     org_jboss_messaging_core_asyncio_impl_AsynchronousFileImpl
 * Method:    closeInternal
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_jboss_messaging_core_asyncio_impl_AsynchronousFileImpl_closeInternal
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jboss_messaging_core_asyncio_impl_AsynchronousFileImpl
 * Method:    stopPoller
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_jboss_messaging_core_asyncio_impl_AsynchronousFileImpl_stopPoller
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jboss_messaging_core_asyncio_impl_AsynchronousFileImpl
 * Method:    internalPollEvents
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_jboss_messaging_core_asyncio_impl_AsynchronousFileImpl_internalPollEvents
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jboss_messaging_core_asyncio_impl_AsynchronousFileImpl
 * Method:    destroyBuffer
 * Signature: (Ljava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_org_jboss_messaging_core_asyncio_impl_AsynchronousFileImpl_destroyBuffer
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_jboss_messaging_core_asyncio_impl_AsynchronousFileImpl
 * Method:    newBuffer
 * Signature: (J)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_org_jboss_messaging_core_asyncio_impl_AsynchronousFileImpl_newBuffer
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
